name: Testing push image to ECR!

on: [push]

# permission can be added at job level or workflow level
permissions:
  id-token: write
  contents: read

jobs:
  PushImageToECR:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      # AWS認証
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.PRAC_AWS_ACOUNT_ID }}:role/prac-github-actions-role
      # ECRへログイン
      - name: Login to Amazon private ECR
        id: login-private-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-private-ecr.outputs.registry }}
          REPOSITORY: prac-github-actions
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY .
          docker push $REGISTRY/$REPOSITORY
